import 'package:flutter/material.dart';
import 'package:mobile_app/db/mock_data.dart';
import 'package:mobile_app/db/database_helper.dart';
import 'package:mobile_app/models/customer.dart';
import 'package:mobile_app/providers/theme_provider.dart';
import 'package:intl/intl.dart';

class RecoveryFormScreen extends StatefulWidget {
  final Customer customer;

  const RecoveryFormScreen({super.key, required this.customer});

  @override
  State<RecoveryFormScreen> createState() => _RecoveryFormScreenState();
}

class _RecoveryFormScreenState extends State<RecoveryFormScreen> {
  final theme = ThemeProvider.instance;
  final _formKey = GlobalKey<FormState>();
  final _receivedAmountCtrl = TextEditingController();
  final _noteCtrl = TextEditingController();
  DateTime _selectedDate = DateTime.now();
  double _creditBalance = 0.0;
  List<Map<String, dynamic>> _staffMembers = [];
  String? _selectedStaff;
  bool _loading = true;

  @override
  void initState() {
    super.initState();
    _loadData();
  }

  @override
  void dispose() {
    _receivedAmountCtrl.dispose();
    _noteCtrl.dispose();
    super.dispose();
  }

  Future<void> _loadData() async {
    try {
      final balance = await DatabaseHelper.instance.getCustomerCreditBalance(widget.customer.id ?? 0);
      final employees = await DatabaseHelper.instance.getEmployees();
      
      if (mounted) {
        setState(() {
          _creditBalance = balance;
          _staffMembers = employees;
          // Pre-select first staff if available
          if (_staffMembers.isNotEmpty) {
            _selectedStaff = _staffMembers.first['name'];
          }
          _loading = false;
        });
      }
    } catch (e) {
      if (mounted) setState(() => _loading = false);
    }
  }

  double get _receivedAmount => double.tryParse(_receivedAmountCtrl.text) ?? 0.0;
  double get _remainingBalance => _creditBalance - _receivedAmount;

  Future<void> _recordPayment() async {
    if (!_formKey.currentState!.validate()) return;

    if (_selectedStaff == null) {
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(
          content: Text('Please select a staff member'),
          backgroundColor: ThemeProvider.error,
        ),
      );
      return;
    }

    if (_receivedAmount <= 0) {
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(
          content: Text('Please enter a valid payment amount'),
          backgroundColor: ThemeProvider.error,
        ),
      );
      return;
    }

    if (_receivedAmount > _creditBalance) {
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(
          content: Text('Payment amount cannot exceed credit balance'),
          backgroundColor: ThemeProvider.error,
        ),
      );
      return;
    }

    final payment = {
      // id will be autogenerated
      'customer_id': widget.customer.id ?? 0,
      'amount': _receivedAmount,
      'received_by': _selectedStaff,
      'payment_date': _selectedDate.toIso8601String(),
      'notes': _noteCtrl.text.trim(),
      'created_at': DateTime.now().toIso8601String(),
    };

    await DatabaseHelper.instance.insertCreditPayment(payment);

    if (mounted) {
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(
          content: Text('Payment recorded successfully'),
          backgroundColor: ThemeProvider.success,
        ),
      );
      Navigator.pop(context, true);
    }
  }

  Future<void> _selectDate() async {
    final picked = await showDatePicker(
      context: context,
      initialDate: _selectedDate,
      firstDate: DateTime(2020),
      lastDate: DateTime.now(),
      builder: (context, child) {
        return Theme(
          data: ThemeData.dark().copyWith(
            colorScheme: ColorScheme.dark(
              primary: theme.highlight,
              surface: theme.surface,
            ),
          ),
          child: child!,
        );
      },
    );
    if (picked != null) {
      setState(() => _selectedDate = picked);
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      extendBodyBehindAppBar: true,
      appBar: AppBar(
        backgroundColor: Colors.transparent,
        elevation: 0,
        title: Text(
          'Record Payment',
          style: TextStyle(
            color: theme.textPrimary,
            fontWeight: FontWeight.w900,
            letterSpacing: -0.5,
          ),
        ),
        leading: BackButton(color: theme.textPrimary),
      ),
      body: theme.glassBackground(
        child: SafeArea(
          child: _loading
            ? Center(child: CircularProgressIndicator(color: theme.highlight))
            : Column(
                children: [
                  Expanded(
                    child: SingleChildScrollView(
                      padding: const EdgeInsets.all(24),
                      child: Form(
                        key: _formKey,
                        child: Column(
                          crossAxisAlignment: CrossAxisAlignment.start,
                          children: [
                            // Customer Info Card
                            Container(
                              padding: const EdgeInsets.all(20),
                              decoration: theme.glassDecoration,
                              child: Row(
                                children: [
                                  Container(
                                    width: 50,
                                    height: 50,
                                    decoration: BoxDecoration(
                                      color: theme.highlight.withOpacity(0.1),
                                      shape: BoxShape.circle,
                                    ),
                                    child: Center(
                                      child: Text(
                                        widget.customer.name[0].toUpperCase(),
                                        style: TextStyle(
                                          color: theme.highlight,
                                          fontSize: 20,
                                          fontWeight: FontWeight.w900,
                                        ),
                                      ),
                                    ),
                                  ),
                                  const SizedBox(width: 16),
                                  Expanded(
                                    child: Column(
                                      crossAxisAlignment: CrossAxisAlignment.start,
                                      children: [
                                        Text(
                                          widget.customer.name,
                                          style: TextStyle(
                                            color: theme.textPrimary,
                                            fontSize: 18,
                                            fontWeight: FontWeight.w800,
                                          ),
                                        ),
                                        Text(
                                          'Customer ID: ${widget.customer.id}',
                                          style: TextStyle(color: theme.textSecondary, fontSize: 12),
                                        ),
                                      ],
                                    ),
                                  ),
                                ],
                              ),
                            ),
                            
                            const SizedBox(height: 24),

                            // Credit Balance Info
                            Container(
                              padding: const EdgeInsets.all(16),
                              decoration: BoxDecoration(
                                color: ThemeProvider.warning.withOpacity(0.1),
                                borderRadius: BorderRadius.circular(16),
                                border: Border.all(color: ThemeProvider.warning.withOpacity(0.3)),
                              ),
                              child: Row(
                                mainAxisAlignment: MainAxisAlignment.spaceBetween,
                                children: [
                                  Column(
                                    crossAxisAlignment: CrossAxisAlignment.start,
                                    children: [
                                      Text(
                                        'TOTAL CREDIT',
                                        style: TextStyle(
                                          color: theme.textHint,
                                          fontSize: 10,
                                          fontWeight: FontWeight.w900,
                                          letterSpacing: 1,
                                        ),
                                      ),
                                      const SizedBox(height: 4),
                                      Text(
                                        '${BusinessConfig.instance.currency}. ${_creditBalance.toStringAsFixed(2)}',
                                        style: const TextStyle(
                                          color: ThemeProvider.warning,
                                          fontSize: 24,
                                          fontWeight: FontWeight.w900,
                                          letterSpacing: -1,
                                        ),
                                      ),
                                    ],
                                  ),
                                  const Icon(Icons.account_balance_wallet_rounded, color: ThemeProvider.warning, size: 32),
                                ],
                              ),
                            ),

                            const SizedBox(height: 24),

                            // Date Field
                            _buildSectionHeader('Payment Date'),
                            const SizedBox(height: 8),
                            _buildDateField(),

                            const SizedBox(height: 20),

                            // Received By Field (Dropdown)
                            _buildSectionHeader('Received By'),
                            const SizedBox(height: 8),
                            _buildStaffDropdown(),

                            const SizedBox(height: 20),

                            // Received Amount Field
                            _buildSectionHeader('Received Amount'),
                            const SizedBox(height: 8),
                            _buildTextField(
                              controller: _receivedAmountCtrl,
                              label: 'Received Amount',
                              icon: Icons.payments_rounded,
                              hint: 'Enter amount',
                              keyboardType: TextInputType.number,
                              onChanged: (v) => setState(() {}),
                            ),

                            const SizedBox(height: 20),

                            // Remaining Balance (Read-only)
                            _buildSectionHeader('Remaining Balance'),
                            const SizedBox(height: 8),
                            Container(
                              padding: const EdgeInsets.all(16),
                              decoration: BoxDecoration(
                                color: _remainingBalance > 0 
                                  ? ThemeProvider.warning.withOpacity(0.1)
                                  : ThemeProvider.success.withOpacity(0.1),
                                borderRadius: BorderRadius.circular(16),
                                border: Border.all(
                                  color: _remainingBalance > 0
                                    ? ThemeProvider.warning.withOpacity(0.3)
                                    : ThemeProvider.success.withOpacity(0.3),
                                ),
                              ),
                              child: Row(
                                children: [
                                  Icon(
                                    _remainingBalance > 0 ? Icons.pending_rounded : Icons.check_circle_rounded,
                                    color: _remainingBalance > 0 ? ThemeProvider.warning : ThemeProvider.success,
                                    size: 20,
                                  ),
                                  const SizedBox(width: 12),
                                  Text(
                                    '${BusinessConfig.instance.currency}. ${_remainingBalance.toStringAsFixed(2)}',
                                    style: TextStyle(
                                      color: _remainingBalance > 0 ? ThemeProvider.warning : ThemeProvider.success,
                                      fontSize: 20,
                                      fontWeight: FontWeight.w900,
                                      letterSpacing: -0.5,
                                    ),
                                  ),
                                ],
                              ),
                            ),

                            const SizedBox(height: 20),

                            // Note Field
                            _buildSectionHeader('Note (Optional)'),
                            const SizedBox(height: 8),
                            _buildTextField(
                              controller: _noteCtrl,
                              label: 'Note',
                              icon: Icons.note_rounded,
                              hint: 'Add a note',
                              maxLines: 3,
                            ),
                          ],
                        ),
                      ),
                    ),
                  ),

                  // Footer Actions
                  Container(
                    padding: const EdgeInsets.all(24),
                    decoration: BoxDecoration(
                      border: Border(top: BorderSide(color: theme.whiteAlpha(0.1))),
                    ),
                    child: Row(
                      children: [
                        Expanded(
                          child: TextButton(
                            onPressed: () => Navigator.pop(context),
                            child: Text(
                              'CANCEL',
                              style: TextStyle(
                                color: theme.textSecondary,
                                fontWeight: FontWeight.w900,
                                letterSpacing: 0.5,
                              ),
                            ),
                          ),
                        ),
                        const SizedBox(width: 12),
                        Expanded(
                          flex: 2,
                          child: ElevatedButton(
                            onPressed: _recordPayment,
                            style: ElevatedButton.styleFrom(
                              backgroundColor: ThemeProvider.success,
                              foregroundColor: Colors.white,
                              padding: const EdgeInsets.symmetric(vertical: 16),
                              elevation: 0,
                              shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(12)),
                            ),
                            child: const Text(
                              'RECORD PAYMENT',
                              style: TextStyle(
                                fontWeight: FontWeight.w900,
                                letterSpacing: 0.5,
                              ),
                            ),
                          ),
                        ),
                      ],
                    ),
                  ),
                ],
              ),
        ),
      ),
    );
  }

  Widget _buildStaffDropdown() {
    return DropdownButtonFormField<String>(
      value: _selectedStaff,
      items: _staffMembers.map((staff) {
        return DropdownMenuItem<String>(
          value: staff['name'],
          child: Text(staff['name'], style: TextStyle(color: theme.textPrimary, fontWeight: FontWeight.w600)),
        );
      }).toList(),
      onChanged: (v) => setState(() => _selectedStaff = v),
      decoration: InputDecoration(
        hintText: 'Select Staff',
        hintStyle: TextStyle(color: theme.textHint),
        prefixIcon: Icon(Icons.person_rounded, color: theme.highlight, size: 20),
        filled: true,
        fillColor: theme.whiteAlpha(0.05),
        border: OutlineInputBorder(
          borderRadius: BorderRadius.circular(16),
          borderSide: BorderSide(color: theme.isDark ? Colors.transparent : Colors.black.withOpacity(0.3)),
        ),
        enabledBorder: OutlineInputBorder(
          borderRadius: BorderRadius.circular(16),
          borderSide: BorderSide(color: theme.isDark ? theme.whiteAlpha(0.1) : Colors.black.withOpacity(0.3)),
        ),
        focusedBorder: OutlineInputBorder(
          borderRadius: BorderRadius.circular(16),
          borderSide: BorderSide(color: theme.isDark ? theme.highlight : Colors.black.withOpacity(0.6), width: 2),
        ),
        contentPadding: const EdgeInsets.symmetric(horizontal: 16, vertical: 16),
      ),
      dropdownColor: theme.surface,
    );
  }

  Widget _buildSectionHeader(String title) {
    return Padding(
      padding: const EdgeInsets.only(left: 4),
      child: Text(
        title.toUpperCase(),
        style: TextStyle(
          color: theme.textSecondary,
          fontSize: 11,
          fontWeight: FontWeight.w900,
          letterSpacing: 1.5,
        ),
      ),
    );
  }

  Widget _buildTextField({
    required TextEditingController controller,
    required String label,
    required IconData icon,
    required String hint,
    TextInputType? keyboardType,
    int maxLines = 1,
    Function(String)? onChanged,
  }) {
    return TextFormField(
      controller: controller,
      keyboardType: keyboardType,
      maxLines: maxLines,
      style: TextStyle(color: theme.textPrimary, fontWeight: FontWeight.w600),
      decoration: InputDecoration(
        hintText: hint,
        hintStyle: TextStyle(color: theme.textHint),
        prefixIcon: Icon(icon, color: theme.highlight, size: 20),
        filled: true,
        fillColor: theme.whiteAlpha(0.05),
        border: OutlineInputBorder(
          borderRadius: BorderRadius.circular(16),
          borderSide: BorderSide(color: theme.isDark ? Colors.transparent : Colors.black.withOpacity(0.3)),
        ),
        enabledBorder: OutlineInputBorder(
          borderRadius: BorderRadius.circular(16),
          borderSide: BorderSide(color: theme.isDark ? theme.whiteAlpha(0.1) : Colors.black.withOpacity(0.3)),
        ),
        focusedBorder: OutlineInputBorder(
          borderRadius: BorderRadius.circular(16),
          borderSide: BorderSide(color: theme.isDark ? theme.highlight : Colors.black.withOpacity(0.6), width: 2),
        ),
        contentPadding: const EdgeInsets.symmetric(horizontal: 16, vertical: 16),
      ),
      onChanged: onChanged,
    );
  }

  Widget _buildDateField() {
    return InkWell(
      onTap: _selectDate,
      borderRadius: BorderRadius.circular(16),
      child: Container(
        padding: const EdgeInsets.all(16),
        decoration: BoxDecoration(
          color: theme.whiteAlpha(0.05),
          borderRadius: BorderRadius.circular(16),
          border: Border.all(color: theme.whiteAlpha(0.1)),
        ),
        child: Row(
          children: [
            Icon(Icons.calendar_today_rounded, color: theme.highlight, size: 20),
            const SizedBox(width: 12),
            Text(
              DateFormat('MMM dd, yyyy').format(_selectedDate),
              style: TextStyle(
                color: theme.textPrimary,
                fontSize: 16,
                fontWeight: FontWeight.w600,
              ),
            ),
            const Spacer(),
            Icon(Icons.arrow_drop_down_rounded, color: theme.iconColor),
          ],
        ),
      ),
    );
  }
}
